# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161205_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic_title',
            field=models.ForeignKey(default='Miscellaneous', null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Topic'),
        ),
    ]
