# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20161205_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic_title',
            field=models.ForeignKey(default='Miscellaneous', on_delete=django.db.models.deletion.CASCADE, to='blog.Topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_title',
            field=models.CharField(default='Miscellaneous', max_length=40, primary_key=True, serialize=False),
        ),
    ]
