# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-05 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161205_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='topic_title',
            new_name='post_topic',
        ),
    ]
