# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-07 03:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20161206_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='number_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='topic_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Topic'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together=set([('username', 'topic_title')]),
        ),
    ]
